# Generated by Django 3.1.2 on 2021-06-14 08:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('activation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField()),
                ('featured', models.BooleanField()),
                ('salary_from', models.FloatField()),
                ('salary_period', models.CharField(choices=[('monthly', 'Monthly'), ('hourly', 'Hourly'), ('weekly', 'Weekly'), ('yearly', 'Yearly')], max_length=7)),
                ('salary_to', models.FloatField()),
                ('company_name', models.CharField(max_length=400)),
                ('logo_url', models.CharField(max_length=500)),
                ('job_admin', models.BooleanField(default=False)),
                ('job_customerservice', models.BooleanField(default=False)),
                ('job_distributionshipping', models.BooleanField(default=False)),
                ('job_grocery', models.BooleanField(default=False)),
                ('job_hospitalityhotel', models.BooleanField(default=False)),
                ('job_covid19', models.BooleanField(default=False)),
                ('job_marketingsales', models.BooleanField(default=False)),
                ('job_other', models.BooleanField(default=False)),
                ('job_production', models.BooleanField(default=False)),
                ('job_restaurantfoodservice', models.BooleanField(default=False)),
                ('job_retail', models.BooleanField(default=False)),
                ('job_supplychain', models.BooleanField(default=False)),
                ('job_transportation', models.BooleanField(default=False)),
                ('job_warehouse', models.BooleanField(default=False)),
                ('employ_fulltime', models.BooleanField(default=False)),
                ('employ_contract', models.BooleanField(default=False)),
                ('employ_parttime', models.BooleanField(default=False)),
                ('employ_adhoc', models.BooleanField(default=False)),
                ('employ_internship', models.BooleanField(default=False)),
            ],
        ),
    ]
